echo "Middlemarch  - George Eliot" >"ZzzzDUMMY__Middlemarch  - George Eliot.mobi"
echo "The Secret History - Donna Tartt" >"ZzzzDUMMY__The Secret History - Donna Tartt.mobi"
echo "The Sound and the Fury  - William Faulkner" >"ZzzzDUMMY__The Sound and the Fury  - William Faulkner.mobi"
echo "A Town Like Alice - Nevil Shute" >"ZzzzDUMMY__A Town Like Alice - Nevil Shute.mobi"
echo "As I Lay Dying - William Faulkner" >"ZzzzDUMMY__As I Lay Dying - William Faulkner.mobi"
echo "Cold Comfort Farm - Stella Gibbons" >"ZzzzDUMMY__Cold Comfort Farm - Stella Gibbons.mobi"
echo "Go Tell It On the Mountain - James Baldwin" >"ZzzzDUMMY__Go Tell It On the Mountain - James Baldwin.mobi"
echo "I, CLAUDIUS - Robert Graves" >"ZzzzDUMMY__I, CLAUDIUS - Robert Graves.mobi"
echo "Light in August - William Faulkner" >"ZzzzDUMMY__Light in August - William Faulkner.mobi"
echo "Sophie’s Choice - William Styron" >"ZzzzDUMMY__Sophie’s Choice - William Styron.mobi"
echo "The Naked and the Dead - Norman Mailer" >"ZzzzDUMMY__The Naked and the Dead - Norman Mailer.mobi"
echo "The World According to Garp - John Irving" >"ZzzzDUMMY__The World According to Garp - John Irving.mobi"
echo "Absalom, Absalom!  - William Faulkner" >"ZzzzDUMMY__Absalom, Absalom!  - William Faulkner.mobi"
echo "Are You There, God? It's me, Margaret - Judy Blume" >"ZzzzDUMMY__Are You There, God? It's me, Margaret - Judy Blume.mobi"
echo "Bel Canto - Ann Patchett" >"ZzzzDUMMY__Bel Canto - Ann Patchett.mobi"
echo "Bridget Jones’s Diary - Helen Fielding" >"ZzzzDUMMY__Bridget Jones’s Diary - Helen Fielding.mobi"
echo "Death Comes for the Archbishop - Willa Cather" >"ZzzzDUMMY__Death Comes for the Archbishop - Willa Cather.mobi"
echo "Deliverance - James Dickey" >"ZzzzDUMMY__Deliverance - James Dickey.mobi"
echo "Far From The Madding Crowd - Thomas Hardy" >"ZzzzDUMMY__Far From The Madding Crowd - Thomas Hardy.mobi"
echo "Main Street - Sinclair Lewis" >"ZzzzDUMMY__Main Street - Sinclair Lewis.mobi"
echo "Silent Spring - Rachel Carson" >"ZzzzDUMMY__Silent Spring - Rachel Carson.mobi"
echo "Swallows and Amazons - Arthur Ransome" >"ZzzzDUMMY__Swallows and Amazons - Arthur Ransome.mobi"
echo "The Adventures of Augie March - Saul Bellow" >"ZzzzDUMMY__The Adventures of Augie March - Saul Bellow.mobi"
echo "The Fault in Our Stars - John Green" >"ZzzzDUMMY__The Fault in Our Stars - John Green.mobi"
echo "The French Lieutenant’s Woman - John Fowles" >"ZzzzDUMMY__The French Lieutenant’s Woman - John Fowles.mobi"
echo "The Golden Notebook  - Doris Lessing" >"ZzzzDUMMY__The Golden Notebook  - Doris Lessing.mobi"
echo "The Magus - John Fowles" >"ZzzzDUMMY__The Magus - John Fowles.mobi"
echo "The Moviegoer - Walker Percy" >"ZzzzDUMMY__The Moviegoer - Walker Percy.mobi"
echo "The Prime of Miss Jean Brodie - Muriel Spark" >"ZzzzDUMMY__The Prime of Miss Jean Brodie - Muriel Spark.mobi"
echo "The Remains of the Day - Kazuo Ishiguro" >"ZzzzDUMMY__The Remains of the Day - Kazuo Ishiguro.mobi"
echo "The Wind-Up Bird Chronicle - A Novel - Haruki Murakami" >"ZzzzDUMMY__The Wind-Up Bird Chronicle - A Novel - Haruki Murakami.mobi"

pause